/** ###################################################################
**     THIS COMPONENT MODULE IS GENERATED BY THE TOOL. DO NOT MODIFY IT.
**     Filename  : _130Hz.H
**     Project   : LowPowerTest_S08QB4
**     Processor : MC9S08QB4CTG
**     Component : TimerInt
**     Version   : Component 02.157, Driver 01.18, CPU db: 3.00.014
**     Compiler  : CodeWarrior HCS08 C Compiler
**     Date/Time : 04.03.2022, 15:46
**     Abstract  :
**         This bean "TimerInt" implements a periodic interrupt.
**         When the bean and its events are enabled, the "OnInterrupt"
**         event is called periodically with the period that you specify.
**         TimerInt supports also changing the period in runtime.
**         The source of periodic interrupt can be timer compare or reload
**         register or timer-overflow interrupt (of free running counter).
**     Settings  :
**         Timer name                  : TPM (16-bit)
**         Compare name                : TPM0
**         Counter shared              : No
**
**         High speed mode
**             Prescaler               : divide-by-1
**             Clock                   : 16384 Hz
**           Initial period/frequency
**             Xtal ticks              : 252
**             microseconds            : 7690
**             milliseconds            : 8
**             seconds (real)          : 0.007690429687
**             Hz                      : 130
**
**         Runtime setting             : none
**
**         Initialization:
**              Timer                  : Disabled
**              Events                 : Disabled
**
**         Timer registers
**              Counter                : TPMCNT    [$0041]
**              Mode                   : TPMSC     [$0040]
**              Run                    : TPMSC     [$0040]
**              Prescaler              : TPMSC     [$0040]
**
**         Compare registers
**              Compare                : TPMC0V    [$0046]
**
**         Flip-flop registers
**              Mode                   : TPMC0SC   [$0045]
**     Contents  :
**         Enable       - byte _130Hz_Enable(void);
**         Disable      - byte _130Hz_Disable(void);
**         EnableEvent  - byte _130Hz_EnableEvent(void);
**         DisableEvent - byte _130Hz_DisableEvent(void);
**
**     Copyright : 1997 - 2009 Freescale Semiconductor, Inc. All Rights Reserved.
**     
**     http      : www.freescale.com
**     mail      : support@freescale.com
** ###################################################################*/

#ifndef ___130Hz
#define ___130Hz

/* MODULE _130Hz. */

/*Include shared modules, which are used for whole project*/
#include "PE_Types.h"
#include "PE_Error.h"
#include "PE_Const.h"
#include "IO_Map.h"
#include "Cpu.h"
extern bool _130Hz_EnEvent;            /* Enable/Disable events */


byte _130Hz_Enable(void);
/*
** ===================================================================
**     Method      :  _130Hz_Enable (component TimerInt)
**
**     Description :
**         This method enables the component - it starts the timer.
**         Events may be generated (<DisableEvent>/<EnableEvent>).
**     Parameters  : None
**     Returns     :
**         ---             - Error code, possible codes:
**                           ERR_OK - OK
**                           ERR_SPEED - This device does not work in
**                           the active speed mode
** ===================================================================
*/

byte _130Hz_Disable(void);
/*
** ===================================================================
**     Method      :  _130Hz_Disable (component TimerInt)
**
**     Description :
**         This method disables the component - it stops the timer. No
**         events will be generated.
**     Parameters  : None
**     Returns     :
**         ---             - Error code, possible codes:
**                           ERR_OK - OK
**                           ERR_SPEED - This device does not work in
**                           the active speed mode
** ===================================================================
*/

#define _130Hz_EnableEvent() (_130Hz_EnEvent = TRUE, (byte)ERR_OK) /* Set the flag "events enabled" */
/*
** ===================================================================
**     Method      :  _130Hz_EnableEvent (component TimerInt)
**
**     Description :
**         This method enables the events.
**     Parameters  : None
**     Returns     :
**         ---             - Error code, possible codes:
**                           ERR_OK - OK
**                           ERR_SPEED - This device does not work in
**                           the active speed mode
** ===================================================================
*/

#define _130Hz_DisableEvent() (_130Hz_EnEvent = FALSE, (byte)ERR_OK) /* Set the flag "events disabled" */
/*
** ===================================================================
**     Method      :  _130Hz_DisableEvent (component TimerInt)
**
**     Description :
**         This method disables the events.
**     Parameters  : None
**     Returns     :
**         ---             - Error code, possible codes:
**                           ERR_OK - OK
**                           ERR_SPEED - This device does not work in
**                           the active speed mode
** ===================================================================
*/

__interrupt void _130Hz_Interrupt(void);
/*
** ===================================================================
**     Method      :  _130Hz_Interrupt (component TimerInt)
**
**     Description :
**         The method services the interrupt of the selected peripheral(s)
**         and eventually invokes the beans event(s).
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/

void _130Hz_Init(void);
/*
** ===================================================================
**     Method      :  _130Hz_Init (component TimerInt)
**
**     Description :
**         Initializes the associated peripheral(s) and the beans 
**         internal variables. The method is called automatically as a 
**         part of the application initialization code.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/


/* END _130Hz. */

#endif /* ifndef ___130Hz */
/*
** ###################################################################
**
**     This file was created by Processor Expert 3.07 [04.34]
**     for the Freescale HCS08 series of microcontrollers.
**
** ###################################################################
*/
