/** ###################################################################
**     THIS COMPONENT MODULE IS GENERATED BY THE TOOL. DO NOT MODIFY IT.
**     Filename  : _20Hz.c
**     Project   : LowPowerTest_S08QB4
**     Processor : MC9S08QB4CTG
**     Component : TimerInt
**     Version   : Component 02.158, Driver 01.20, CPU db: 3.00.014
**     Compiler  : CodeWarrior HCS08 C Compiler
**     Date/Time : 24.02.2016, 10:37
**     Abstract  :
**         This component "TimerInt" implements a periodic interrupt.
**         When the component and its events are enabled, the "OnInterrupt"
**         event is called periodically with the period that you specify.
**         TimerInt supports also changing the period in runtime.
**         The source of periodic interrupt can be timer compare or reload
**         register or timer-overflow interrupt (of free running counter).
**     Settings  :
**         Timer name                  : MTIM (8-bit)
**         Compare name                : MTIMmod
**         Counter shared              : No
**
**         High speed mode
**             Prescaler               : divide-by-4
**             Clock                   : 4096 Hz
**           Initial period/frequency
**             Xtal ticks              : 1632
**             microseconds            : 49805
**             milliseconds            : 50
**             seconds (real)          : 0.0498046875
**             Hz                      : 20
**
**         Runtime setting             : none
**
**         Initialization:
**              Timer                  : Disabled
**              Events                 : Disabled
**
**         Timer registers
**              Counter                : MTIMCNT   [$003E]
**              Mode                   : MTIMSC    [$003C]
**              Run                    : MTIMSC    [$003C]
**              Prescaler              : MTIMCLK   [$003D]
**
**         Compare registers
**              Compare                : MTIMMOD   [$003F]
**
**         Flip-flop registers
**     Contents  :
**         Enable       - byte _20Hz_Enable(void);
**         Disable      - byte _20Hz_Disable(void);
**         EnableEvent  - byte _20Hz_EnableEvent(void);
**         DisableEvent - byte _20Hz_DisableEvent(void);
**
**     Copyright : 1997 - 2010 Freescale Semiconductor, Inc. All Rights Reserved.
**     
**     http      : www.freescale.com
**     mail      : support@freescale.com
** ###################################################################*/

/* MODULE _20Hz. */

#include "Events.h"
#include "PE_Error.h"
#include "_20Hz.h"
#pragma MESSAGE DISABLE C2705          /* WARNING C2705: Possible loss of data */
#pragma MESSAGE DISABLE C5919          /* WARNING C5919: Conversion of floating to unsigned integral */
#pragma MESSAGE DISABLE C5703          /* WARNING C5703: Parameter X declared in function F but not referenced */
#pragma MESSAGE DISABLE C4002          /* Disable warning C4002 "Result not used" */

static bool EnUser;                    /* Enable device by user */
bool _20Hz_EnEvent;                    /* Enable/Disable events */
/*** Internal macros and method prototypes ***/

/*
** ===================================================================
**     Method      :  SetPV (component TimerInt)
**
**     Description :
**         The method sets prescaler of the device.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
#define _20Hz_SetPV(_Val) \
MTIMCLK = (byte)(_Val);                /* Store given value to the prescaler and set clock source*/\
MTIMSC_TRST = 0x01;                    /* Reset counter */

/*
** ===================================================================
**     Method      :  SetCV (component TimerInt)
**
**     Description :
**         The method computes and sets compare eventually modulo value 
**         for time measuring.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
#define _20Hz_SetCV(_Val) \
  (MTIMMOD = (byte)(_Val))

/*
** ===================================================================
**     Method      :  HWEnDi (component TimerInt)
**
**     Description :
**         Enables or disables the peripheral(s) associated with the 
**         component. The method is called automatically as a part of the 
**         Enable and Disable methods and several internal methods.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
static void HWEnDi(void);


/*** End of internal method prototypes ***/

/*
** ===================================================================
**     Method      :  HWEnDi (component TimerInt)
**
**     Description :
**         Enables or disables the peripheral(s) associated with the 
**         component. The method is called automatically as a part of the 
**         Enable and Disable methods and several internal methods.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
static void HWEnDi(void)
{
  if (EnUser) {
    /* MTIMSC: TOF=0,TOIE=1,TRST=1,TSTP=0,??=0,??=0,??=0,??=0 */
    setReg8(MTIMSC, 0x60);             /* Reset and start counter; Enable interrupt */ 
  } else {
    /* MTIMSC: TOF=0,TOIE=0,TRST=0,TSTP=1,??=0,??=0,??=0,??=0 */
    setReg8(MTIMSC, 0x10);             /* Disable Overflow interrupt and Stop counter */ 
  }
}

/*
** ===================================================================
**     Method      :  _20Hz_Enable (component TimerInt)
**
**     Description :
**         This method enables the component - it starts the timer.
**         Events may be generated (<DisableEvent>/<EnableEvent>).
**     Parameters  : None
**     Returns     :
**         ---             - Error code, possible codes:
**                           ERR_OK - OK
**                           ERR_SPEED - This device does not work in
**                           the active speed mode
** ===================================================================
*/
byte _20Hz_Enable(void)
{
  if (!EnUser) {                       /* Is the device disabled by user? */
    EnUser = TRUE;                     /* If yes then set the flag "device enabled" */
    HWEnDi();                          /* Enable the device */
  }
  return ERR_OK;                       /* OK */
}

/*
** ===================================================================
**     Method      :  _20Hz_Disable (component TimerInt)
**
**     Description :
**         This method disables the component - it stops the timer. No
**         events will be generated.
**     Parameters  : None
**     Returns     :
**         ---             - Error code, possible codes:
**                           ERR_OK - OK
**                           ERR_SPEED - This device does not work in
**                           the active speed mode
** ===================================================================
*/
byte _20Hz_Disable(void)
{
  if (EnUser) {                        /* Is the device enabled by user? */
    EnUser = FALSE;                    /* If yes then set the flag "device disabled" */
    HWEnDi();                          /* Disable the device */
  }
  return ERR_OK;                       /* OK */
}

/*
** ===================================================================
**     Method      :  _20Hz_EnableEvent (component TimerInt)
**
**     Description :
**         This method enables the events.
**     Parameters  : None
**     Returns     :
**         ---             - Error code, possible codes:
**                           ERR_OK - OK
**                           ERR_SPEED - This device does not work in
**                           the active speed mode
** ===================================================================
*/
/*
byte _20Hz_EnableEvent(void)

**      This method is implemented as a macro. See header module. **
*/

/*
** ===================================================================
**     Method      :  _20Hz_DisableEvent (component TimerInt)
**
**     Description :
**         This method disables the events.
**     Parameters  : None
**     Returns     :
**         ---             - Error code, possible codes:
**                           ERR_OK - OK
**                           ERR_SPEED - This device does not work in
**                           the active speed mode
** ===================================================================
*/
/*
byte _20Hz_DisableEvent(void)

**      This method is implemented as a macro. See header module. **
*/

/*
** ===================================================================
**     Method      :  _20Hz_Init (component TimerInt)
**
**     Description :
**         Initializes the associated peripheral(s) and the component 
**         internal variables. The method is called automatically as a 
**         part of the application initialization code.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
void _20Hz_Init(void)
{
  /* MTIMSC: TOF=0,TOIE=0,TRST=0,TSTP=1,??=0,??=0,??=0,??=0 */
  setReg8(MTIMSC, 0x10);               /* Stop timer */ 
  EnUser = FALSE;                      /* Disable device */
  _20Hz_EnEvent = FALSE;               /* Disable event */
  _20Hz_SetCV(0xCB);                   /* Inicialize appropriate value to the compare/modulo/reload register */
  _20Hz_SetPV((byte)0x02);             /* Set prescaler and clock source */
  HWEnDi();
}


/*
** ===================================================================
**     Method      :  _20Hz_Interrupt (component TimerInt)
**
**     Description :
**         The method services the interrupt of the selected peripheral(s)
**         and eventually invokes the component event(s).
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
ISR(_20Hz_Interrupt)
{
  /* MTIMSC: TOF=0 */
  clrReg8Bits(MTIMSC, 0x80);           /* Reset overflow interrupt request flag */ 
  if (_20Hz_EnEvent) {                 /* Are the events enabled? */
    _20Hz_OnInterrupt();               /* Invoke user event */
  }
}



/* END _20Hz. */

/*
** ###################################################################
**
**     This file was created by Processor Expert 3.09 [04.41]
**     for the Freescale HCS08 series of microcontrollers.
**
** ###################################################################
*/
