<<<<<<< HEAD
/** ###################################################################
**     THIS COMPONENT MODULE IS GENERATED BY THE TOOL. DO NOT MODIFY IT.
**     Filename  : _5VOnOff.H
**     Project   : LowPowerTest_S08QB4
**     Processor : MC9S08QB4CTG
**     Component : BitIO
**     Version   : Component 02.075, Driver 03.21, CPU db: 3.00.014
**     Compiler  : CodeWarrior HCS08 C Compiler
**     Date/Time : 04.03.2022, 15:46
**     Abstract  :
**         This bean "BitIO" implements an one-bit input/output.
**         It uses one bit/pin of a port.
**         Note: This bean is set to work in Output direction only.
**         Methods of this bean are mostly implemented as a macros
**         (if supported by target language and compiler).
**     Settings  :
**         Used pin                    :
**             ----------------------------------------------------
**                Number (on package)  |    Name
**             ----------------------------------------------------
**                       12            |  PTB0_KBIP4_RxD_ADP4
**             ----------------------------------------------------
**
**         Port name                   : PTB
**
**         Bit number (in port)        : 0
**         Bit mask of the port        : $0001
**
**         Initial direction           : Output (direction cannot be changed)
**         Initial output value        : 0
**         Initial pull option         : off
**
**         Port data register          : PTBD      [$0002]
**         Port control register       : PTBDD     [$0003]
**
**         Optimization for            : speed
**     Contents  :
**         GetVal - bool _5VOnOff_GetVal(void);
**         PutVal - void _5VOnOff_PutVal(bool Val);
**         ClrVal - void _5VOnOff_ClrVal(void);
**         SetVal - void _5VOnOff_SetVal(void);
**         NegVal - void _5VOnOff_NegVal(void);
**
**     Copyright : 1997 - 2009 Freescale Semiconductor, Inc. All Rights Reserved.
**     
**     http      : www.freescale.com
**     mail      : support@freescale.com
** ###################################################################*/

#ifndef _5VOnOff_H_
#define _5VOnOff_H_

/* MODULE _5VOnOff. */

  /* Including shared modules, which are used in the whole project */
#include "PE_Types.h"
#include "PE_Error.h"
#include "PE_Const.h"
#include "IO_Map.h"
#include "Cpu.h"


/*
** ===================================================================
**     Method      :  _5VOnOff_GetVal (component BitIO)
**
**     Description :
**         This method returns an input value.
**           a) direction = Input  : reads the input value from the
**                                   pin and returns it
**           b) direction = Output : returns the last written value
**         Note: This bean is set to work in Output direction only.
**     Parameters  : None
**     Returns     :
**         ---             - Input value. Possible values:
**                           FALSE - logical "0" (Low level)
**                           TRUE - logical "1" (High level)

** ===================================================================
*/
#define _5VOnOff_GetVal() ( \
    (bool)((getReg8(PTBD) & 0x01))     /* Return port data */ \
  )

/*
** ===================================================================
**     Method      :  _5VOnOff_PutVal (component BitIO)
**
**     Description :
**         This method writes the new output value.
**     Parameters  :
**         NAME       - DESCRIPTION
**         Val             - Output value. Possible values:
**                           FALSE - logical "0" (Low level)
**                           TRUE - logical "1" (High level)
**     Returns     : Nothing
** ===================================================================
*/
void _5VOnOff_PutVal(bool Val);

/*
** ===================================================================
**     Method      :  _5VOnOff_ClrVal (component BitIO)
**
**     Description :
**         This method clears (sets to zero) the output value.
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/
#define _5VOnOff_ClrVal() ( \
    (void)clrReg8Bits(PTBD, 0x01)      /* PTBD0=0x00 */ \
  )

/*
** ===================================================================
**     Method      :  _5VOnOff_SetVal (component BitIO)
**
**     Description :
**         This method sets (sets to one) the output value.
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/
#define _5VOnOff_SetVal() ( \
    (void)setReg8Bits(PTBD, 0x01)      /* PTBD0=0x01 */ \
  )

/*
** ===================================================================
**     Method      :  _5VOnOff_NegVal (component BitIO)
**
**     Description :
**         This method negates (inverts) the output value.
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/
#define _5VOnOff_NegVal() ( \
    (void)invertReg8Bits(PTBD, 0x01)   /* PTBD0=invert */ \
  )



/* END _5VOnOff. */
#endif /* #ifndef ___5VOnOff_H_ */
/*
** ###################################################################
**
**     This file was created by Processor Expert 3.07 [04.34]
**     for the Freescale HCS08 series of microcontrollers.
**
** ###################################################################
*/
=======
/** ###################################################################
**     THIS COMPONENT MODULE IS GENERATED BY THE TOOL. DO NOT MODIFY IT.
**     Filename  : _5VOnOff.H
**     Project   : LowPowerTest_S08QB4
**     Processor : MC9S08QB4CTG
**     Component : BitIO
**     Version   : Component 02.075, Driver 03.21, CPU db: 3.00.014
**     Compiler  : CodeWarrior HCS08 C Compiler
**     Date/Time : 04.03.2022, 15:46
**     Abstract  :
**         This bean "BitIO" implements an one-bit input/output.
**         It uses one bit/pin of a port.
**         Note: This bean is set to work in Output direction only.
**         Methods of this bean are mostly implemented as a macros
**         (if supported by target language and compiler).
**     Settings  :
**         Used pin                    :
**             ----------------------------------------------------
**                Number (on package)  |    Name
**             ----------------------------------------------------
**                       12            |  PTB0_KBIP4_RxD_ADP4
**             ----------------------------------------------------
**
**         Port name                   : PTB
**
**         Bit number (in port)        : 0
**         Bit mask of the port        : $0001
**
**         Initial direction           : Output (direction cannot be changed)
**         Initial output value        : 0
**         Initial pull option         : off
**
**         Port data register          : PTBD      [$0002]
**         Port control register       : PTBDD     [$0003]
**
**         Optimization for            : speed
**     Contents  :
**         GetVal - bool _5VOnOff_GetVal(void);
**         PutVal - void _5VOnOff_PutVal(bool Val);
**         ClrVal - void _5VOnOff_ClrVal(void);
**         SetVal - void _5VOnOff_SetVal(void);
**         NegVal - void _5VOnOff_NegVal(void);
**
**     Copyright : 1997 - 2009 Freescale Semiconductor, Inc. All Rights Reserved.
**     
**     http      : www.freescale.com
**     mail      : support@freescale.com
** ###################################################################*/

#ifndef _5VOnOff_H_
#define _5VOnOff_H_

/* MODULE _5VOnOff. */

  /* Including shared modules, which are used in the whole project */
#include "PE_Types.h"
#include "PE_Error.h"
#include "PE_Const.h"
#include "IO_Map.h"
#include "Cpu.h"


/*
** ===================================================================
**     Method      :  _5VOnOff_GetVal (component BitIO)
**
**     Description :
**         This method returns an input value.
**           a) direction = Input  : reads the input value from the
**                                   pin and returns it
**           b) direction = Output : returns the last written value
**         Note: This bean is set to work in Output direction only.
**     Parameters  : None
**     Returns     :
**         ---             - Input value. Possible values:
**                           FALSE - logical "0" (Low level)
**                           TRUE - logical "1" (High level)

** ===================================================================
*/
#define _5VOnOff_GetVal() ( \
    (bool)((getReg8(PTBD) & 0x01))     /* Return port data */ \
  )

/*
** ===================================================================
**     Method      :  _5VOnOff_PutVal (component BitIO)
**
**     Description :
**         This method writes the new output value.
**     Parameters  :
**         NAME       - DESCRIPTION
**         Val             - Output value. Possible values:
**                           FALSE - logical "0" (Low level)
**                           TRUE - logical "1" (High level)
**     Returns     : Nothing
** ===================================================================
*/
void _5VOnOff_PutVal(bool Val);

/*
** ===================================================================
**     Method      :  _5VOnOff_ClrVal (component BitIO)
**
**     Description :
**         This method clears (sets to zero) the output value.
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/
#define _5VOnOff_ClrVal() ( \
    (void)clrReg8Bits(PTBD, 0x01)      /* PTBD0=0x00 */ \
  )

/*
** ===================================================================
**     Method      :  _5VOnOff_SetVal (component BitIO)
**
**     Description :
**         This method sets (sets to one) the output value.
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/
#define _5VOnOff_SetVal() ( \
    (void)setReg8Bits(PTBD, 0x01)      /* PTBD0=0x01 */ \
  )

/*
** ===================================================================
**     Method      :  _5VOnOff_NegVal (component BitIO)
**
**     Description :
**         This method negates (inverts) the output value.
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/
#define _5VOnOff_NegVal() ( \
    (void)invertReg8Bits(PTBD, 0x01)   /* PTBD0=invert */ \
  )



/* END _5VOnOff. */
#endif /* #ifndef ___5VOnOff_H_ */
/*
** ###################################################################
**
**     This file was created by Processor Expert 3.07 [04.34]
**     for the Freescale HCS08 series of microcontrollers.
**
** ###################################################################
*/
>>>>>>> ee6fccc69f14bc60ee1207c6c470af86ffbbb5ff
