/** ###################################################################
**     THIS COMPONENT MODULE IS GENERATED BY THE TOOL. DO NOT MODIFY IT.
**     Filename  : EInt1.C
**     Project   : LowPowerTest_S08QB4
**     Processor : MC9S08QB4CTG
**     Component : ExtInt
**     Version   : Component 02.094, Driver 01.19, CPU db: 3.00.014
**     Compiler  : CodeWarrior HCS08 C Compiler
**     Date/Time : 04.03.2022, 15:46
**     Abstract  :
**         This bean "ExtInt" implements an external 
**         interrupt, its control methods and interrupt/event 
**         handling procedure.
**         The bean uses one pin which generates interrupt on 
**         selected edge.
**     Settings  :
**         Interrupt name              : Vkeyboard
**         User handling procedure     : EInt1_OnInterrupt
**
**         Used pin                    :
**             ----------------------------------------------------
**                Number (on package)  |    Name
**             ----------------------------------------------------
**                       16            |  PTA0_KBIP0_TPMCH0_ADP0_ACMPPLUS
**             ----------------------------------------------------
**
**         Port name                   : PTA
**
**         Bit number (in port)        : 0
**         Bit mask of the port        : $0001
**
**         Signal edge/level           : falling
**         Priority                    : 
**         Pull option                 : up
**         Initial state               : Disabled
**
**         Edge register               : KBIES     [$000E]
**         Enable register             : KBIPE     [$000D]
**         Request register            : KBISC     [$000C]
**
**         Port data register          : PTAD      [$0000]
**         Port control register       : PTADD     [$0001]
**     Contents  :
**         Enable  - void EInt1_Enable(void);
**         Disable - void EInt1_Disable(void);
**         GetVal  - bool EInt1_GetVal(void);
**
**     Copyright : 1997 - 2009 Freescale Semiconductor, Inc. All Rights Reserved.
**     
**     http      : www.freescale.com
**     mail      : support@freescale.com
** ###################################################################*/

#include "EInt1.h"

/*Including shared modules, which are used for all project*/

#include "Events.h"
#include "Cpu.h"


/*
** ===================================================================
**     Method      :  EInt1_Enable (component ExtInt)
**
**     Description :
**         Enable the bean - the external events are accepted. This
**         method is enabled only if HW module allows enable/disable of
**         the interrupt.
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/
/*
void EInt1_Enable(void)

**      This method is implemented as macro. See EInt1.h file.      **
*/

/*
** ===================================================================
**     Method      :  EInt1_Disable (component ExtInt)
**
**     Description :
**         Disable the bean - the external events are not accepted.
**         This method is enabled only if HW module allows
**         enable/disable of the interrupt.
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/
/*
void EInt1_Disable(void)

**      This method is implemented as macro. See EInt1.h file.      **
*/

/*
** ===================================================================
**     Method      :  EInt1_Interrupt (component ExtInt)
**
**     Description :
**         The method services the interrupt of the selected peripheral(s)
**         and eventually invokes the beans event(s).
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
ISR(EInt1_Interrupt)
{
  KBISC_KBACK = 1;                     /* Clear the interrupt flag */
  EInt1_OnInterrupt();                 /* Invoke user event */
}

/*
** ===================================================================
**     Method      :  EInt1_GetVal (component ExtInt)
**
**     Description :
**         Returns the actual value of the input pin of the bean.
**     Parameters  : None
**     Returns     :
**         ---             - Returned input value. Possible values:
**                           FALSE - logical "0" (Low level)
**                           TRUE - logical "1" (High level)
** ===================================================================
*/
/*
bool EInt1_GetVal(void)

**      This method is implemented as macro. See EInt1.h file.      **
*/

/*
** ###################################################################
**
**     This file was created by Processor Expert 3.07 [04.34]
**     for the Freescale HCS08 series of microcontrollers.
**
** ###################################################################
*/
