<<<<<<< HEAD
/** ###################################################################
**     THIS COMPONENT MODULE IS GENERATED BY THE TOOL. DO NOT MODIFY IT.
**     Filename  : EInt1.H
**     Project   : LowPowerTest_S08QB4
**     Processor : MC9S08QB4CTG
**     Component : ExtInt
**     Version   : Component 02.094, Driver 01.19, CPU db: 3.00.014
**     Compiler  : CodeWarrior HCS08 C Compiler
**     Date/Time : 04.03.2022, 15:46
**     Abstract  :
**         This bean "ExtInt" implements an external 
**         interrupt, its control methods and interrupt/event 
**         handling procedure.
**         The bean uses one pin which generates interrupt on 
**         selected edge.
**     Settings  :
**         Interrupt name              : Vkeyboard
**         User handling procedure     : EInt1_OnInterrupt
**
**         Used pin                    :
**             ----------------------------------------------------
**                Number (on package)  |    Name
**             ----------------------------------------------------
**                       16            |  PTA0_KBIP0_TPMCH0_ADP0_ACMPPLUS
**             ----------------------------------------------------
**
**         Port name                   : PTA
**
**         Bit number (in port)        : 0
**         Bit mask of the port        : $0001
**
**         Signal edge/level           : falling
**         Priority                    : 
**         Pull option                 : up
**         Initial state               : Disabled
**
**         Edge register               : KBIES     [$000E]
**         Enable register             : KBIPE     [$000D]
**         Request register            : KBISC     [$000C]
**
**         Port data register          : PTAD      [$0000]
**         Port control register       : PTADD     [$0001]
**     Contents  :
**         Enable  - void EInt1_Enable(void);
**         Disable - void EInt1_Disable(void);
**         GetVal  - bool EInt1_GetVal(void);
**
**     Copyright : 1997 - 2009 Freescale Semiconductor, Inc. All Rights Reserved.
**     
**     http      : www.freescale.com
**     mail      : support@freescale.com
** ###################################################################*/

#ifndef __EInt1_H
#define __EInt1_H

/* MODULE EInt1. */



/*Including shared modules, which are used in the whole project*/
#include "PE_Types.h"
#include "PE_Error.h"
#include "PE_Const.h"
#include "IO_Map.h"
#include "Events.h"
#include "Cpu.h"


#define EInt1_Enable() \
  (KBISC_KBACK = 0x01,KBISC_KBIE = 0x01)
/*
** ===================================================================
**     Method      :  EInt1_Enable (component ExtInt)
**
**     Description :
**         Enable the bean - the external events are accepted. This
**         method is enabled only if HW module allows enable/disable of
**         the interrupt.
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/

#define EInt1_Disable() \
  (KBISC_KBIE = 0)

/*
** ===================================================================
**     Method      :  EInt1_Disable (component ExtInt)
**
**     Description :
**         Disable the bean - the external events are not accepted.
**         This method is enabled only if HW module allows
**         enable/disable of the interrupt.
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/

__interrupt void EInt1_Interrupt(void);
/*
** ===================================================================
**     Method      :  EInt1_Interrupt (component ExtInt)
**
**     Description :
**         The method services the interrupt of the selected peripheral(s)
**         and eventually invokes the beans event(s).
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/

#define EInt1_GetVal() \
  ((bool)((PTAD) & 0x01))

/*
** ===================================================================
**     Method      :  EInt1_GetVal (component ExtInt)
**
**     Description :
**         Returns the actual value of the input pin of the bean.
**     Parameters  : None
**     Returns     :
**         ---             - Returned input value. Possible values:
**                           FALSE - logical "0" (Low level)
**                           TRUE - logical "1" (High level)
** ===================================================================
*/
#endif /* __EInt1_H*/
/*
** ###################################################################
**
**     This file was created by Processor Expert 3.07 [04.34]
**     for the Freescale HCS08 series of microcontrollers.
**
** ###################################################################
*/
=======
/** ###################################################################
**     THIS COMPONENT MODULE IS GENERATED BY THE TOOL. DO NOT MODIFY IT.
**     Filename  : EInt1.H
**     Project   : LowPowerTest_S08QB4
**     Processor : MC9S08QB4CTG
**     Component : ExtInt
**     Version   : Component 02.094, Driver 01.19, CPU db: 3.00.014
**     Compiler  : CodeWarrior HCS08 C Compiler
**     Date/Time : 04.03.2022, 15:46
**     Abstract  :
**         This bean "ExtInt" implements an external 
**         interrupt, its control methods and interrupt/event 
**         handling procedure.
**         The bean uses one pin which generates interrupt on 
**         selected edge.
**     Settings  :
**         Interrupt name              : Vkeyboard
**         User handling procedure     : EInt1_OnInterrupt
**
**         Used pin                    :
**             ----------------------------------------------------
**                Number (on package)  |    Name
**             ----------------------------------------------------
**                       16            |  PTA0_KBIP0_TPMCH0_ADP0_ACMPPLUS
**             ----------------------------------------------------
**
**         Port name                   : PTA
**
**         Bit number (in port)        : 0
**         Bit mask of the port        : $0001
**
**         Signal edge/level           : falling
**         Priority                    : 
**         Pull option                 : up
**         Initial state               : Disabled
**
**         Edge register               : KBIES     [$000E]
**         Enable register             : KBIPE     [$000D]
**         Request register            : KBISC     [$000C]
**
**         Port data register          : PTAD      [$0000]
**         Port control register       : PTADD     [$0001]
**     Contents  :
**         Enable  - void EInt1_Enable(void);
**         Disable - void EInt1_Disable(void);
**         GetVal  - bool EInt1_GetVal(void);
**
**     Copyright : 1997 - 2009 Freescale Semiconductor, Inc. All Rights Reserved.
**     
**     http      : www.freescale.com
**     mail      : support@freescale.com
** ###################################################################*/

#ifndef __EInt1_H
#define __EInt1_H

/* MODULE EInt1. */



/*Including shared modules, which are used in the whole project*/
#include "PE_Types.h"
#include "PE_Error.h"
#include "PE_Const.h"
#include "IO_Map.h"
#include "Events.h"
#include "Cpu.h"


#define EInt1_Enable() \
  (KBISC_KBACK = 0x01,KBISC_KBIE = 0x01)
/*
** ===================================================================
**     Method      :  EInt1_Enable (component ExtInt)
**
**     Description :
**         Enable the bean - the external events are accepted. This
**         method is enabled only if HW module allows enable/disable of
**         the interrupt.
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/

#define EInt1_Disable() \
  (KBISC_KBIE = 0)

/*
** ===================================================================
**     Method      :  EInt1_Disable (component ExtInt)
**
**     Description :
**         Disable the bean - the external events are not accepted.
**         This method is enabled only if HW module allows
**         enable/disable of the interrupt.
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/

__interrupt void EInt1_Interrupt(void);
/*
** ===================================================================
**     Method      :  EInt1_Interrupt (component ExtInt)
**
**     Description :
**         The method services the interrupt of the selected peripheral(s)
**         and eventually invokes the beans event(s).
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/

#define EInt1_GetVal() \
  ((bool)((PTAD) & 0x01))

/*
** ===================================================================
**     Method      :  EInt1_GetVal (component ExtInt)
**
**     Description :
**         Returns the actual value of the input pin of the bean.
**     Parameters  : None
**     Returns     :
**         ---             - Returned input value. Possible values:
**                           FALSE - logical "0" (Low level)
**                           TRUE - logical "1" (High level)
** ===================================================================
*/
#endif /* __EInt1_H*/
/*
** ###################################################################
**
**     This file was created by Processor Expert 3.07 [04.34]
**     for the Freescale HCS08 series of microcontrollers.
**
** ###################################################################
*/
>>>>>>> ee6fccc69f14bc60ee1207c6c470af86ffbbb5ff
