/** ###################################################################
**     THIS COMPONENT MODULE IS GENERATED BY THE TOOL. DO NOT MODIFY IT.
**     Filename  : T5_OnOff.H
**     Project   : LowPowerTest_S08QB4
**     Processor : MC9S08QB4CTG
**     Component : BitIO
**     Version   : Component 02.075, Driver 03.21, CPU db: 3.00.014
**     Compiler  : CodeWarrior HCS08 C Compiler
**     Date/Time : 04.03.2022, 15:46
**     Abstract  :
**         This bean "BitIO" implements an one-bit input/output.
**         It uses one bit/pin of a port.
**         Note: This bean is set to work in Output direction only.
**         Methods of this bean are mostly implemented as a macros
**         (if supported by target language and compiler).
**     Settings  :
**         Used pin                    :
**             ----------------------------------------------------
**                Number (on package)  |    Name
**             ----------------------------------------------------
**                       11            |  PTB1_KBIP5_TxD_ADP5
**             ----------------------------------------------------
**
**         Port name                   : PTB
**
**         Bit number (in port)        : 1
**         Bit mask of the port        : $0002
**
**         Initial direction           : Output (direction cannot be changed)
**         Initial output value        : 0
**         Initial pull option         : off
**
**         Port data register          : PTBD      [$0002]
**         Port control register       : PTBDD     [$0003]
**
**         Optimization for            : speed
**     Contents  :
**         GetVal - bool T5_OnOff_GetVal(void);
**         PutVal - void T5_OnOff_PutVal(bool Val);
**         ClrVal - void T5_OnOff_ClrVal(void);
**         SetVal - void T5_OnOff_SetVal(void);
**
**     Copyright : 1997 - 2009 Freescale Semiconductor, Inc. All Rights Reserved.
**     
**     http      : www.freescale.com
**     mail      : support@freescale.com
** ###################################################################*/

#ifndef T5_OnOff_H_
#define T5_OnOff_H_

/* MODULE T5_OnOff. */

  /* Including shared modules, which are used in the whole project */
#include "PE_Types.h"
#include "PE_Error.h"
#include "PE_Const.h"
#include "IO_Map.h"
#include "Cpu.h"


/*
** ===================================================================
**     Method      :  T5_OnOff_GetVal (component BitIO)
**
**     Description :
**         This method returns an input value.
**           a) direction = Input  : reads the input value from the
**                                   pin and returns it
**           b) direction = Output : returns the last written value
**         Note: This bean is set to work in Output direction only.
**     Parameters  : None
**     Returns     :
**         ---             - Input value. Possible values:
**                           FALSE - logical "0" (Low level)
**                           TRUE - logical "1" (High level)

** ===================================================================
*/
#define T5_OnOff_GetVal() ( \
    (bool)((getReg8(PTBD) & 0x02))     /* Return port data */ \
  )

/*
** ===================================================================
**     Method      :  T5_OnOff_PutVal (component BitIO)
**
**     Description :
**         This method writes the new output value.
**     Parameters  :
**         NAME       - DESCRIPTION
**         Val             - Output value. Possible values:
**                           FALSE - logical "0" (Low level)
**                           TRUE - logical "1" (High level)
**     Returns     : Nothing
** ===================================================================
*/
void T5_OnOff_PutVal(bool Val);

/*
** ===================================================================
**     Method      :  T5_OnOff_ClrVal (component BitIO)
**
**     Description :
**         This method clears (sets to zero) the output value.
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/
#define T5_OnOff_ClrVal() ( \
    (void)clrReg8Bits(PTBD, 0x02)      /* PTBD1=0x00 */ \
  )

/*
** ===================================================================
**     Method      :  T5_OnOff_SetVal (component BitIO)
**
**     Description :
**         This method sets (sets to one) the output value.
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/
#define T5_OnOff_SetVal() ( \
    (void)setReg8Bits(PTBD, 0x02)      /* PTBD1=0x01 */ \
  )



/* END T5_OnOff. */
#endif /* #ifndef __T5_OnOff_H_ */
/*
** ###################################################################
**
**     This file was created by Processor Expert 3.07 [04.34]
**     for the Freescale HCS08 series of microcontrollers.
**
** ###################################################################
*/
