/** ###################################################################
**     THIS COMPONENT MODULE IS GENERATED BY THE TOOL. DO NOT MODIFY IT.
**     Filename  : Vectors.C
**     Project   : LowPowerTest_S08QB4
**     Processor : MC9S08QB4CTG
**     Version   : Component 01.004, Driver 01.35, CPU db: 3.00.014
**     Compiler  : CodeWarrior HCS08 C Compiler
**     Date/Time : 04.03.2022, 15:46
**     Abstract  :
**         This bean "MC9S08QB8_16" contains initialization of the
**         CPU and provides basic methods and events for CPU core
**         settings.
**     Settings  :
**
**
**     Copyright : 1997 - 2009 Freescale Semiconductor, Inc. All Rights Reserved.
**     
**     http      : www.freescale.com
**     mail      : support@freescale.com
** ###################################################################*/


#include "Cpu.h"
#include "_130Hz.h"
#include "drive_Reed.h"
#include "EInt1.h"
#include "_2750ms.h"
#include "send.h"
#include "_5VOnOff.h"
#include "T5_OnOff.h"
#include "_100Hz.h"
#include "Bit1.h"
extern near void _EntryPoint(void);

void (* near const _vect[])(void) @0xFFCE = { /* Interrupt vector table */
         _2750ms_Interrupt,            /* Int.no. 24 Vrtc (at FFCE)                  Used */
         Cpu_Interrupt,                /* Int.no. 23 VReserved23 (at FFD0)           Unassigned */
         Cpu_Interrupt,                /* Int.no. 22 VReserved22 (at FFD2)           Unassigned */
         Cpu_Interrupt,                /* Int.no. 21 VReserved21 (at FFD4)           Unassigned */
         Cpu_Interrupt,                /* Int.no. 20 Vacmp (at FFD6)                 Unassigned */
         Cpu_Interrupt,                /* Int.no. 19 Vadc (at FFD8)                  Unassigned */
         EInt1_Interrupt,              /* Int.no. 18 Vkeyboard (at FFDA)             Used */
         Cpu_Interrupt,                /* Int.no. 17 VReserved17 (at FFDC)           Unassigned */
         Cpu_Interrupt,                /* Int.no. 16 Vscitx (at FFDE)                Unassigned */
         Cpu_Interrupt,                /* Int.no. 15 Vscirx (at FFE0)                Unassigned */
         Cpu_Interrupt,                /* Int.no. 14 Vscierr (at FFE2)               Unassigned */
         Cpu_Interrupt,                /* Int.no. 13 VReserved13 (at FFE4)           Unassigned */
         _100Hz_Interrupt,             /* Int.no. 12 Vmtim (at FFE6)                 Used */
         Cpu_Interrupt,                /* Int.no. 11 VReserved11 (at FFE8)           Unassigned */
         Cpu_Interrupt,                /* Int.no. 10 VReserved10 (at FFEA)           Unassigned */
         Cpu_Interrupt,                /* Int.no.  9 VReserved9 (at FFEC)            Unassigned */
         Cpu_Interrupt,                /* Int.no.  8 VReserved8 (at FFEE)            Unassigned */
         Cpu_Interrupt,                /* Int.no.  7 Vtpmovf (at FFF0)               Unassigned */
         Cpu_Interrupt,                /* Int.no.  6 VReserved6 (at FFF2)            Unassigned */
         Cpu_Interrupt,                /* Int.no.  5 VReserved5 (at FFF4)            Unassigned */
         _130Hz_Interrupt,             /* Int.no.  4 Vtpmch0 (at FFF6)               Used */
         Cpu_Interrupt,                /* Int.no.  3 Vlvd (at FFF8)                  Unassigned */
         Cpu_Interrupt,                /* Int.no.  2 Virq (at FFFA)                  Unassigned */
         Cpu_Interrupt,                /* Int.no.  1 Vswi (at FFFC)                  Unassigned */
         _EntryPoint                   /* Int.no.  0 Vreset (at FFFE)                Reset vector */
};
/*
** ###################################################################
**
**     This file was created by Processor Expert 3.07 [04.34]
**     for the Freescale HCS08 series of microcontrollers.
**
** ###################################################################
*/

